clear_tree: true
counter_detection_range: 1
desired_speed: 5
max_planning_time: 10
maximum_range: 3000
search_bounds:
  points:
  - x: 0
    y: 0
    z: 0
  - x: 100
    y: -28
    z: 0
  - x: 230
    y: 0
    z: 0
  - x: 250
    y: 100
    z: 0
  - x: 130
    y: 156
    z: 0
  - x: 110
    y: 191
    z: 0
  - x: -40
    y: 141
    z: 0
start_pose:
  orientation:
    w: 0
    x: 0
    y: 0
    z: 1.0
  position:
    x: 0.0
    y: 0.0
    z: 30
target_priors:
- grid_prior:
    bounds:
      points:
      - x: 0
        y: 0
        z: 0
      - x: 100
        y: -28
        z: 0
      - x: 230
        y: 0
        z: 0
      - x: 250
        y: 100
        z: 0
      - x: 130
        y: 156
        z: 0
      - x: 110
        y: 191
        z: 0
      - x: -40
        y: 141
        z: 0
    confidence: 0.2
    grid_prior_type: 1
    header:
      frame_id: local_enu
    priority: 1.0
    sensor_model_id: 0
- grid_prior:
    bounds:
      points:
      - x: 0
        y: 160
        z: 0
      - x: 12
        y: 135
        z: 0
      - x: 92
        y: 150
        z: 0
      - x: 80
        y: 175
        z: 0
    confidence: 0.5
    grid_prior_type: 1
    header:
      frame_id: local_enu
    priority: 10.0
    sensor_model_id: 0

# keep out zone
keep_out_zones:
  - 
    header: 
      frame_id: "local_enu"
    x: 0
    y: 139
    radius: 15
  - 
    header: 
      frame_id: "local_enu"
    x: 192
    y: -21
    radius: 10
  - 
    header: 
      frame_id: "local_enu"
    x: 210
    y: -10
    radius: 8