node_loop_hz: 2  # in seconds

# Can limit the rate of publishing the map to the search belief map visualization
# Useful to limit the size of bags or when limited bandwidth
search_belief_publishing_every_n_loops: 20  # number of loops.

plan_request_topic: "planner/plan_request"
agent_odom_topic: "odometry"
image_with_cam_pose_topic: "image_to_project"

map_resolution: 1.0
map_resolution_num: 100 # used if proportional parameters is set in tigris.yaml
confidence_threshold: 0.5

# Time based rewards parameters (linear function with a floor)
time_decay_slope: 0 # must be negative. Decrease in scale value per second
time_decay_floor: 1 # minimum scalar value from time decay

update_from_image_projection: true

# Visualization
update_from_image_projection: false
visualization: true
visualization_alpha: 0.3
