name: build-workspace-master

on:
  push:
    branches:
      - master
      - fix-github-action-master
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  run-master:
    runs-on: [self-hosted]
    container: 
      image: bradygm/ipp-github-build
    if: "always() && !contains(github.event.head_commit.message, 'DO-NOT-RUN')"
    steps:
    - name: update-github-repos
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_TOKEN:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "github@github.com"
        git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }}"; echo "password=${GITHUB_TOKEN}"; }; f'

        if [ ! -d ws_master/src/ipp_planners ]; then
          echo "ipp_planners repo does not exist."
          mkdir -p ws_master/src
          cd ws_master/src
          git clone https://github.com/castacks/ipp_planners.git
          cd ../../
        fi

        cd ws_master/src/ipp_planners
        git checkout master
        git fetch
        git pull
        cd ../
        echo "Cloning other repos"
        temp_file=$(mktemp)
        bash ../../ws/src/ipp_planners/scripts/ssh_to_http_repos.bash ../../ws/src/ipp_planners/ws_master.repos > $temp_file
        vcs import < $temp_file
        vcs pull

    - name: build workspace
      run: |
        cd ws_master/
        catkin config --extend /opt/ros/$ROS_DISTRO 
        catkin build

  run-production:
    runs-on: [self-hosted]
    container: 
      image: bradygm/ipp-github-build
    if: "always() && !contains(github.event.head_commit.message, 'DO-NOT-RUN')"
    steps:
    - name: update-github-repos
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_TOKEN:  ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "github@github.com"
        git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }}"; echo "password=${GITHUB_TOKEN}"; }; f'

        if [ ! -d ws_production/src/ipp_planners ]; then
          echo "ipp_planners repo does not exist."
          mkdir -p ws_production/src
          cd ws_production/src
          git clone https://github.com/castacks/ipp_planners.git
          cd ../../
        fi

        cd ws_production/src
        echo "Cloning other repos"
        temp_file=$(mktemp)
        bash ../../ws/src/ipp_planners/scripts/ssh_to_http_repos.bash ../../ws/src/ipp_planners/ws_production.repos > $temp_file
        vcs import < $temp_file
        vcs pull

    - name: build workspace
      run: |
        cd ws_production/
        catkin config --extend /opt/ros/$ROS_DISTRO 
        catkin build