# Testing parameters for MC testing, quantitative results collection

planner_types:
# - greedy
# - random
# - rpmcts
# - rimcts
# - limcts
# - greedy
- tigris
# - rect_coverage
# - mcts_search
# - primtreebnb
# - primtree
# - greedy
# - random

number_of_trials: 25  #


# If you want to execute the plan in sim or not. 
# Set to true for collecting quant results, set to false for generating training data
execute_plan: True # Just want the first plan
log_search_map_metrics: True #If we want to record search map metrics. Will only be used if execute_plan is also true 
sample_plan_request_randomly: True # Send plan request instead 
reset_map_every_plan_request: True # Reset map every plan request

min_num_targets: 4
max_num_targets: 20
min_sigma: 2
max_sigma: 15
min_confidence: 0.05
max_confidence: 0.5

map_bounds: 5000

drone_speed: 50.0
planning_time: 10.0 # sample?
min_budget: 15000  
max_budget: 15000

# seed_1: [606354, 503946, 792822]
# seed_2: [590872, 356327, 937327]

seed_1: [4186, 35385, 66366, 4161, 35341, 822580, 20829, 96028, 4803, 77504, 5658, 43731, 8287, 9929, 469918, 513, 8198, 84315, 1108, 30322, 260479, 935394, 606354, 50946, 79282]
seed_2: [33620, 298547, 140157, 60920, 832928, 84703, 25830, 301255, 150410, 85816, 368361, 69942, 24346, 39779, 320437, 25877, 76497, 6171, 67588, 166402, 924190, 383780, 590872, 356327, 937327]
