
# ROS Node params
pause_while_planning: false  # whether to not propagate the real time belief when planning. used for research experiments
loop_rate: 2.0
publish_metrics: true  # true or false

# Input topics
filtered_targets_topic: "filtered_targets"

# Output topics
belief_output_topic: "particle_filters_belief"
variance_output_topic: "total_variance"

# whether killed particles should be resampled from existing particles. if false, then killed particles remain dead. 
resample_killed_particles: true
# whether to reinitialize based on actual new targets received
reinit_real_positive_observations: true  
# the maximum variance we consider to be worth reducing. variance gets transformed by: floor(var, variance_cap) / variance_cap 
variance_cap: 100000

# Belief update parameters
min_z_accept_filtered_targets: 30 # drone must be at least this height to process filtered targets. this helps with noise
max_target_position_variance: 100  # max position variance of incoming filtered targets, anything above this will be rejected
max_target_velocity_variance: 10 # max velocity variance of incoming filtered targets, anything above rejected
distance_strictness: 0.000005  # association strictness for what counts as a match. decrease this to have less particle filters spawn
softmax_beta: 5.0  # how much to prefer the maximum match over lower alternatives for attracting particle filters

# Target Propagation parameters
num_particles: 200
steps_per_second: 1


# Visuals
marker_scale: 50
# by default alpha is set to 1/150. you can scale this up to make it less transparent if you want. setting the multiplier to num_particles means no transparency
marker_alpha_multiplier: 1.0  



class_controls:
  - class_label: ship
    class_id: 0
    linear_acceleration_mean: 0.0  # WARNING: make sure this is a double, or will crash
    angular_velocity_mean: 0.0  # make sure this is a double
    linear_acceleration_std: 0.0
    angular_velocity_std: 0.025