# MCTS-base config, to be included after planner.yaml
# all other similarly named *mcts.yaml's are SYMLINKED using ln -sT mcts.yaml [specific]mcts.yaml. so they share parameters
gen_train_data: "$(arg gen_train_data)"

# max_rollout_depth: 100  
max_rollout_depth: 50  
# num_actions: 10
num_actions: 10  # the first N-target actions are directly at the mean
# exploration_weight: 0.0
# exploration_weight: 0.141421356  # sqrt(2) * 0.1
# exploration_weight: 0.8
exploration_weight: 1.0
# exploration_weight: 1.41421356  # sqrt(2)
# exploration_weight: 10  
# exploration_weight: 20  
# exploration_weight: 40  
# exploration_weight: 50  

limcts_torchscript_file: "./torchscript_modules/limcts_explicit-mean_epoch=509-val_loss=4.4120E-04.pt"
# lpmcts_torchscript_file: "./torchscript_modules/lpmcts_andrew-sagar-epoch=1026-val_loss=3.6159E-03.pt"