
#!/bin/bash

#echo commands to stdout

set -x

echo "Running task number $SLURM_ARRAY_TASK_ID"

# create sigularity container
source /etc/profile.d/modules.sh

singularity instance start \
    --net --network none \
    -B /storage2/datasets/bradym/test_results \
    /home/bradym/singularity_images/ipp-dev.sif \
    ipp-brady-${SLURM_ARRAY_JOB_ID}-${SLURM_ARRAY_TASK_ID}

singularity exec instance://ipp-brady-${SLURM_ARRAY_JOB_ID}-${SLURM_ARRAY_TASK_ID} 'bash' /home/bradym/run_mc_testing.sh




#END

