# planning parameters
clear_tree: True
max_planning_time: 5.0
maximum_range: 64716.0117188
desired_speed: 18.0
counter_detection_range: 50.0
min_loiter_radius: 500.0
wind_speed: 
  x: 0.0
  y: 0.0
  z: 0.0

# drone
start_pose: 
  position: 
    x: -93.1802384961
    y: 285.168381663
    z: 0.00293299052163
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.809504369178
    w: 0.587113852912
current_speed: 
  x: 0.0
  y: 0.0
  z: 0.0

# sensor
sensor_constraints: 
  min_direction: 
    x: -2.0
    y: -2.0
    z: -2.0
  max_direction: 
    x: -2.0
    y: -2.0
    z: -2.0
  min_field_of_regard_horizontal: -2.0
  max_field_of_regard_horizontal: -1.0
  min_field_of_regard_vertical: -2.0
  max_field_of_regard_vertical: -1.0

# map
search_bounds: 
  points: 
    - 
      x: -2798.76855469
      y: -1055.69848633
      z: 0.0
    - 
      x: -2798.98754883
      y: -1055.78137207
      z: 0.0
    - 
      x: -851.009216309
      y: 85.3252029419
      z: 0.0
    - 
      x: -851.228271484
      y: 85.2422485352
      z: 0.0
    - 
      x: 933.829528809
      y: 1905.56848145
      z: 0.0
    - 
      x: 933.610412598
      y: 1905.48547363
      z: 0.0
    - 
      x: 1443.80908203
      y: 1411.97106934
      z: 0.0
    - 
      x: 1443.59008789
      y: 1411.88806152
      z: 0.0
    - 
      x: 331.364532471
      y: -562.554382324
      z: 0.0
    - 
      x: 331.145446777
      y: -562.637329102
      z: 0.0
    - 
      x: -225.101165771
      y: -685.950622559
      z: 0.0
    - 
      x: -225.320251465
      y: -686.033569336
      z: 0.0
    - 
      x: -735.36328125
      y: -2629.53417969
      z: 0.0
    - 
      x: -735.582336426
      y: -2629.6171875
      z: 0.0
    - 
      x: -2590.45703125
      y: -2073.7878418
      z: 0.0
    - 
      x: -2590.67602539
      y: -2073.87084961
      z: 0.0


# target priors
target_priors: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1663867531
        nsecs: 609695762
      frame_id: "planner"
    grid_prior: 
      header: 
        seq: 0
        stamp: 
          secs: 1663867531
          nsecs: 609696973
        frame_id: "planner"
      grid_prior_type: 3
      bounds: 
        points: 
          - 
            x: -1480.85046387
            y: -1069.63916016
            z: -126.251548767
      confidence: 0.5
      priority: 10.0
      sensor_model_id: 1
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1663867531
        nsecs: 609725184
      frame_id: "planner"
    grid_prior: 
      header: 
        seq: 0
        stamp: 
          secs: 1663867531
          nsecs: 609725326
        frame_id: "planner"
      grid_prior_type: 3
      bounds: 
        points: 
          - 
            x: 522.28918457
            y: 1195.93664551
            z: -126.123733521
      confidence: 0.5
      priority: 2.0
      sensor_model_id: 1
clear_tree: True


planner_params:
  header: 
      seq: 0
      stamp: 
        secs: 1663867531
        nsecs: 609695762
      frame_id: "planner"
  prob_sample_track: 0.3
  track_reward_weight: 0.001
  search_reward_weight: 13.2
  strict_stay_in_bounds: false