
# planning parameters
clear_tree: True
max_planning_time: 20.0
maximum_range: 1000.0
desired_speed: 9
counter_detection_range: 0.0
min_loiter_radius: 500.0
wind_speed: 
  x: 0.0
  y: 0.0
  z: 0.0

# drone
start_pose: 
  position: 
    x: 69.97805769614146
    y: 50.389424260531285
    z: 49.99921224814149
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
current_speed: 
  x: 12.0
  y: 9.0
  z: 0.1

# sensor
sensor_constraints: 
  min_direction: 
    x: -2.0
    y: -2.0
    z: -2.0
  max_direction: 
    x: -2.0
    y: -2.0
    z: -2.0
  min_field_of_regard_horizontal: -2.0
  max_field_of_regard_horizontal: -1.0
  min_field_of_regard_vertical: -2.0
  max_field_of_regard_vertical: -1.0

# map
search_bounds: 
  points: 
    - 
      x: 252.57211
      y: 0.003135301
      z: -0.0039765597
    - 
      x: 252.56038
      y: 611.50275
      z: -0.030340945
    - 
      x: -1.2076384e-10
      y: 611.50024
      z: -0.026364576
    - 
      x: 0.002169072
      y: 0.0006398405
      z: -1.2873932e-09

# target priors
target_priors: 
  - 
    grid_prior: 
      header: 
        frame_id: "local_enu"
      grid_prior_type: 3
      bounds: 
        points:
          - 
            x: 42.167908
            y: 290.08865
            z: 602.99304
      confidence: .5
      priority: 10
      sensor_model_id: 1
  - 
    grid_prior: 
      header: 
        frame_id: "local_enu"
      grid_prior_type: 3
      bounds: 
        points:
          - 
            x: 216.19327
            y: 358.22263
            z: 602.986
      confidence: .5
      priority: 9
      sensor_model_id: 1
  - 
    grid_prior: 
      header: 
        frame_id: "local_enu"
      grid_prior_type: 3
      bounds: 
        points:
          - 
            x: 137.84413
            y: 556.2574
            z: 602.97394
      confidence: .5
      priority: 8
      sensor_model_id: 1
  - 
    grid_prior: 
      header: 
        frame_id: "local_enu"
      grid_prior_type: 2
      bounds: 
        points:
          - 
            x: 77.91478
            y: 46.224464
            z: 604.8384
          - 
            x: 81.142395
            y: 61.32037
            z: 649.99896
          - 
            x: 87.11436
            y: 96.81138
            z: 649.9985
          - 
            x: 86.158035
            y: 135.11014
            z: 649.9978
      confidence: .5
      priority: 1.149999976158142
      sensor_model_id: 1