# Testing parameters for MC testing, quantitative results collection

planner_types:
# - greedy
# - random
# - rpmcts
# - rimcts
# - limcts
# - lpmcts
# - tigris
- tracking

number_of_trials: 3  #


# If you want to execute the plan in sim or not. 
# Set to true for collecting quant results, set to false for generating training data
execute_plan: False # Just want the first plan
sample_plan_request_randomly: False # Send plan request instead 